version: "3.9"

services:
  db:
    container_name: db
    image: postgres:14
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data
